declare module 'vue-simple-icons' {
  import { Component } from 'vue'

  export const NetIcon: Component
  export const I1PasswordIcon: Component
  export const I500pxIcon: Component
  export const AbbRobotStudioIcon: Component
  export const AboutMeIcon: Component
  export const AbstractIcon: Component
  export const AcademiaIcon: Component
  export const AccusoftIcon: Component
  export const AcmIcon: Component
  export const ActiGraphIcon: Component
  export const ActivisionIcon: Component
  export const AddThisIcon: Component
  export const AdGuardIcon: Component
  export const AdobeIcon: Component
  export const AdobeAcrobatReaderIcon: Component
  export const AdobeAfterEffectsIcon: Component
  export const AdobeAuditionIcon: Component
  export const AdobeCreativeCloudIcon: Component
  export const AdobeDreamweaverIcon: Component
  export const AdobeIllustratorIcon: Component
  export const AdobeInDesignIcon: Component
  export const AdobeLightroomCcIcon: Component
  export const AdobeLightroomClassicIcon: Component
  export const AdobePhoneGapIcon: Component
  export const AdobePhotoshopIcon: Component
  export const AdobePremiereIcon: Component
  export const AdobeTypekitIcon: Component
  export const AdobeXdIcon: Component
  export const AdonisJsIcon: Component
  export const AffinityIcon: Component
  export const AffinityDesignerIcon: Component
  export const AffinityPhotoIcon: Component
  export const AffinityPublisherIcon: Component
  export const AiqfomeIcon: Component
  export const AirbnbIcon: Component
  export const AirbusIcon: Component
  export const AircallIcon: Component
  export const AirPlayAudioIcon: Component
  export const AirPlayVideoIcon: Component
  export const AirtableIcon: Component
  export const AlgoliaIcon: Component
  export const AlipayIcon: Component
  export const AlliedModdersIcon: Component
  export const AlloCinIcon: Component
  export const AlpineLinuxIcon: Component
  export const AmazonIcon: Component
  export const AmazonAlexaIcon: Component
  export const AmazonAwsIcon: Component
  export const AmazonLumberyardIcon: Component
  export const AmdIcon: Component
  export const AmericanExpressIcon: Component
  export const AnacondaIcon: Component
  export const AnalogueIcon: Component
  export const AnchorIcon: Component
  export const AndelaIcon: Component
  export const AndroidIcon: Component
  export const AndroidStudioIcon: Component
  export const AngelListIcon: Component
  export const AngularIcon: Component
  export const AngularUniversalIcon: Component
  export const AngularJsIcon: Component
  export const AnsibleIcon: Component
  export const ApacheIcon: Component
  export const ApacheAirflowIcon: Component
  export const ApacheAntIcon: Component
  export const ApacheCordovaIcon: Component
  export const ApacheEChartsIcon: Component
  export const ApacheFlinkIcon: Component
  export const ApacheKafkaIcon: Component
  export const ApacheMavenIcon: Component
  export const ApacheNetBeansIdeIcon: Component
  export const ApacheOpenOfficeIcon: Component
  export const ApachePulsarIcon: Component
  export const ApacheRocketMqIcon: Component
  export const ApacheSolrIcon: Component
  export const ApacheSparkIcon: Component
  export const AppleIcon: Component
  export const AppleMusicIcon: Component
  export const ApplePayIcon: Component
  export const ApplePodcastsIcon: Component
  export const AppVeyorIcon: Component
  export const AralIcon: Component
  export const ArchLinuxIcon: Component
  export const ArchiveOfOurOwnIcon: Component
  export const ArduinoIcon: Component
  export const ArtStationIcon: Component
  export const ArXivIcon: Component
  export const AsanaIcon: Component
  export const AsciidoctorIcon: Component
  export const AsciinemaIcon: Component
  export const AtTIcon: Component
  export const AtlassianIcon: Component
  export const AtomIcon: Component
  export const AudiIcon: Component
  export const AudibleIcon: Component
  export const AudiomackIcon: Component
  export const AureliaIcon: Component
  export const Auth0Icon: Component
  export const AuthyIcon: Component
  export const AutomaticIcon: Component
  export const AutotaskIcon: Component
  export const AventrixIcon: Component
  export const AwesomeWmIcon: Component
  export const AzureArtifactsIcon: Component
  export const AzureDevOpsIcon: Component
  export const AzurePipelinesIcon: Component
  export const BabelIcon: Component
  export const BaiduIcon: Component
  export const BambooIcon: Component
  export const BancontactIcon: Component
  export const BandcampIcon: Component
  export const BandLabIcon: Component
  export const BandsintownIcon: Component
  export const BasecampIcon: Component
  export const BathAsuIcon: Component
  export const BattleNetIcon: Component
  export const BeatportIcon: Component
  export const BeatsIcon: Component
  export const BeatsByDreIcon: Component
  export const BehanceIcon: Component
  export const BigCartelIcon: Component
  export const BingIcon: Component
  export const BitIcon: Component
  export const BitbucketIcon: Component
  export const BitcoinIcon: Component
  export const BitdefenderIcon: Component
  export const BitlyIcon: Component
  export const BitriseIcon: Component
  export const BlackberryIcon: Component
  export const BlenderIcon: Component
  export const BloggerIcon: Component
  export const BluetoothIcon: Component
  export const BmcSoftwareIcon: Component
  export const BoeingIcon: Component
  export const BoostIcon: Component
  export const BootstrapIcon: Component
  export const BowerIcon: Component
  export const BoxIcon: Component
  export const BrandAiIcon: Component
  export const BrandfolderIcon: Component
  export const BraveIcon: Component
  export const BreakerIcon: Component
  export const BroadcomIcon: Component
  export const BuddyIcon: Component
  export const BufferIcon: Component
  export const BugsnagIcon: Component
  export const BulmaIcon: Component
  export const BuyMeACoffeeIcon: Component
  export const BuzzFeedIcon: Component
  export const CIcon: Component
  export const CSharpIcon: Component
  export const CplusplusIcon: Component
  export const CakePhpIcon: Component
  export const CampaignMonitorIcon: Component
  export const CanvaIcon: Component
  export const CashAppIcon: Component
  export const CassandraIcon: Component
  export const CastoramaIcon: Component
  export const CastroIcon: Component
  export const CdProjektIcon: Component
  export const CeleryIcon: Component
  export const CentOsIcon: Component
  export const CevoIcon: Component
  export const ChartMogulIcon: Component
  export const ChaseIcon: Component
  export const ChefIcon: Component
  export const Cinema_4DIcon: Component
  export const CircleIcon: Component
  export const CircleCiIcon: Component
  export const CirrusCiIcon: Component
  export const CiscoIcon: Component
  export const CitrixIcon: Component
  export const CitroNIcon: Component
  export const CiviCrmIcon: Component
  export const ClarisIcon: Component
  export const ClockifyIcon: Component
  export const ClojureIcon: Component
  export const CloudBeesIcon: Component
  export const CloudflareIcon: Component
  export const CMakeIcon: Component
  export const CoOpIcon: Component
  export const CodacyIcon: Component
  export const CodeClimateIcon: Component
  export const CodecademyIcon: Component
  export const CodeChefIcon: Component
  export const CodecovIcon: Component
  export const CodeFactorIcon: Component
  export const CodeforcesIcon: Component
  export const CodeIgniterIcon: Component
  export const CodePenIcon: Component
  export const CoderwallIcon: Component
  export const CodeSandboxIcon: Component
  export const CodeshipIcon: Component
  export const CodewarsIcon: Component
  export const CodioIcon: Component
  export const CoffeeScriptIcon: Component
  export const CoinbaseIcon: Component
  export const CommonWorkflowLanguageIcon: Component
  export const ComposerIcon: Component
  export const ComproPagoIcon: Component
  export const ConcourseIcon: Component
  export const CondaForgeIcon: Component
  export const ConektaIcon: Component
  export const ConfluenceIcon: Component
  export const ConvertioIcon: Component
  export const CoronaEngineIcon: Component
  export const CoronaRendererIcon: Component
  export const CourseraIcon: Component
  export const CoverallsIcon: Component
  export const CPanelIcon: Component
  export const CreativeCommonsIcon: Component
  export const CrehanaIcon: Component
  export const CrunchbaseIcon: Component
  export const CrunchyrollIcon: Component
  export const CryengineIcon: Component
  export const CssWizardryIcon: Component
  export const Css3Icon: Component
  export const CurlIcon: Component
  export const D3JsIcon: Component
  export const DailymotionIcon: Component
  export const DartIcon: Component
  export const DasErsteIcon: Component
  export const DashlaneIcon: Component
  export const DassaultSystMesIcon: Component
  export const DataCampIcon: Component
  export const DatadogIcon: Component
  export const DaznIcon: Component
  export const DblpIcon: Component
  export const DebianIcon: Component
  export const DeepinIcon: Component
  export const DeezerIcon: Component
  export const DeliciousIcon: Component
  export const DeliverooIcon: Component
  export const DellIcon: Component
  export const DenoIcon: Component
  export const DependabotIcon: Component
  export const DesignerNewsIcon: Component
  export const DevToIcon: Component
  export const DeviantArtIcon: Component
  export const DevRantIcon: Component
  export const DiasporaIcon: Component
  export const DiggIcon: Component
  export const DigitalOceanIcon: Component
  export const DirectusIcon: Component
  export const DiscogsIcon: Component
  export const DiscordIcon: Component
  export const DiscourseIcon: Component
  export const DiscoverIcon: Component
  export const DisqusIcon: Component
  export const DisrootIcon: Component
  export const DjangoIcon: Component
  export const DlnaIcon: Component
  export const DockerIcon: Component
  export const DocuSignIcon: Component
  export const DolbyIcon: Component
  export const DoubanIcon: Component
  export const DraugiemLvIcon: Component
  export const DribbbleIcon: Component
  export const DroneIcon: Component
  export const DropboxIcon: Component
  export const DrupalIcon: Component
  export const DTubeIcon: Component
  export const DuckDuckGoIcon: Component
  export const DunkedIcon: Component
  export const DuolingoIcon: Component
  export const Dynamics_365Icon: Component
  export const DynatraceIcon: Component
  export const EaIcon: Component
  export const EBayIcon: Component
  export const EclipseIdeIcon: Component
  export const ElasticIcon: Component
  export const ElasticCloudIcon: Component
  export const ElasticStackIcon: Component
  export const ElasticsearchIcon: Component
  export const ElectronIcon: Component
  export const ElementaryIcon: Component
  export const EleventyIcon: Component
  export const ElixirIcon: Component
  export const ElloIcon: Component
  export const ElsevierIcon: Component
  export const EmberJsIcon: Component
  export const EmbyIcon: Component
  export const EmlakjetIcon: Component
  export const EmpireKredIcon: Component
  export const EnvatoIcon: Component
  export const EpelIcon: Component
  export const EpicGamesIcon: Component
  export const EpsonIcon: Component
  export const EseaIcon: Component
  export const EsLintIcon: Component
  export const EthereumIcon: Component
  export const EtsyIcon: Component
  export const EventStoreIcon: Component
  export const EventbriteIcon: Component
  export const EvernoteIcon: Component
  export const EverplacesIcon: Component
  export const EvryIcon: Component
  export const ExercismIcon: Component
  export const ExpertsExchangeIcon: Component
  export const ExpoIcon: Component
  export const EyeEmIcon: Component
  export const FDroidIcon: Component
  export const FSecureIcon: Component
  export const FacebookIcon: Component
  export const FaceitIcon: Component
  export const FandangoIcon: Component
  export const FandomIcon: Component
  export const FastlyIcon: Component
  export const FavroIcon: Component
  export const FeatHubIcon: Component
  export const FedoraIcon: Component
  export const FedRampIcon: Component
  export const FeedlyIcon: Component
  export const FerrariIcon: Component
  export const FerrariNVIcon: Component
  export const FidoAllianceIcon: Component
  export const FifaIcon: Component
  export const FigmaIcon: Component
  export const FigshareIcon: Component
  export const FilaIcon: Component
  export const FileZillaIcon: Component
  export const FirebaseIcon: Component
  export const FitbitIcon: Component
  export const FiteIcon: Component
  export const FiverrIcon: Component
  export const FlaskIcon: Component
  export const FlattrIcon: Component
  export const FlickrIcon: Component
  export const FlipboardIcon: Component
  export const FloatplaneIcon: Component
  export const FloodIcon: Component
  export const FluentdIcon: Component
  export const FlutterIcon: Component
  export const FnacIcon: Component
  export const FontAwesomeIcon: Component
  export const FormstackIcon: Component
  export const FortinetIcon: Component
  export const FossaIcon: Component
  export const FossilScmIcon: Component
  export const FoursquareIcon: Component
  export const FramerIcon: Component
  export const FreeBsdIcon: Component
  export const FreeCodeCampIcon: Component
  export const FreelancerIcon: Component
  export const FujifilmIcon: Component
  export const FujitsuIcon: Component
  export const FurAffinityIcon: Component
  export const FurryNetworkIcon: Component
  export const GarminIcon: Component
  export const GatsbyIcon: Component
  export const GaugesIcon: Component
  export const GeniusIcon: Component
  export const GentooIcon: Component
  export const GeocachingIcon: Component
  export const GerritIcon: Component
  export const GhostIcon: Component
  export const GimpIcon: Component
  export const GitIcon: Component
  export const GiteaIcon: Component
  export const GitHubIcon: Component
  export const GitLabIcon: Component
  export const GitpodIcon: Component
  export const GitterIcon: Component
  export const GlassdoorIcon: Component
  export const GlitchIcon: Component
  export const GmailIcon: Component
  export const GnomeIcon: Component
  export const GnuIcon: Component
  export const GnuBashIcon: Component
  export const GnuEmacsIcon: Component
  export const GnuIceCatIcon: Component
  export const GnuPrivacyGuardIcon: Component
  export const GnuSocialIcon: Component
  export const GoIcon: Component
  export const GodotEngineIcon: Component
  export const GogComIcon: Component
  export const GoldenLineIcon: Component
  export const GoodreadsIcon: Component
  export const GoogleIcon: Component
  export const GoogleAdsIcon: Component
  export const GoogleAnalyticsIcon: Component
  export const GoogleAssistantIcon: Component
  export const GoogleCardboardIcon: Component
  export const GoogleCastIcon: Component
  export const GoogleChromeIcon: Component
  export const GoogleClassroomIcon: Component
  export const GoogleCloudIcon: Component
  export const GoogleDriveIcon: Component
  export const GoogleFitIcon: Component
  export const GoogleHangoutsIcon: Component
  export const GoogleHangoutsChatIcon: Component
  export const GoogleKeepIcon: Component
  export const GoogleLensIcon: Component
  export const GoogleMapsIcon: Component
  export const GoogleMessagesIcon: Component
  export const GoogleMyBusinessIcon: Component
  export const GoogleNearbyIcon: Component
  export const GooglePayIcon: Component
  export const GooglePlayIcon: Component
  export const GooglePodcastsIcon: Component
  export const GoogleScholarIcon: Component
  export const GoogleSearchConsoleIcon: Component
  export const GoogleSheetsIcon: Component
  export const GoogleTagManagerIcon: Component
  export const GoogleTranslateIcon: Component
  export const GovUkIcon: Component
  export const GradleIcon: Component
  export const GrafanaIcon: Component
  export const GraphcoolIcon: Component
  export const GraphQlIcon: Component
  export const GravIcon: Component
  export const GravatarIcon: Component
  export const GreenkeeperIcon: Component
  export const GreenSockIcon: Component
  export const GroovyIcon: Component
  export const GrouponIcon: Component
  export const GruntIcon: Component
  export const GulpIcon: Component
  export const GumroadIcon: Component
  export const GumtreeIcon: Component
  export const GutenbergIcon: Component
  export const HabrIcon: Component
  export const HackadayIcon: Component
  export const HackerEarthIcon: Component
  export const HackerOneIcon: Component
  export const HackerRankIcon: Component
  export const HackHandsIcon: Component
  export const HacksterIcon: Component
  export const HappyCowIcon: Component
  export const HashnodeIcon: Component
  export const HaskellIcon: Component
  export const HatenaBookmarkIcon: Component
  export const HaveibeenpwnedIcon: Component
  export const HaxeIcon: Component
  export const HelloFreshIcon: Component
  export const HelmIcon: Component
  export const HereIcon: Component
  export const HerokuIcon: Component
  export const HexoIcon: Component
  export const HighlyIcon: Component
  export const HipChatIcon: Component
  export const HitachiIcon: Component
  export const HockeyAppIcon: Component
  export const HomeAssistantIcon: Component
  export const HomifyIcon: Component
  export const HootsuiteIcon: Component
  export const HoudiniIcon: Component
  export const HouzzIcon: Component
  export const HpIcon: Component
  export const HtmlAcademyIcon: Component
  export const Html5Icon: Component
  export const HuaweiIcon: Component
  export const HubSpotIcon: Component
  export const HugoIcon: Component
  export const HuluIcon: Component
  export const HumbleBundleIcon: Component
  export const HurriyetemlakIcon: Component
  export const HypothesisIcon: Component
  export const IataIcon: Component
  export const IbmIcon: Component
  export const ICloudIcon: Component
  export const IcoMoonIcon: Component
  export const IconIcon: Component
  export const IconJarIcon: Component
  export const IcqIcon: Component
  export const IDealIcon: Component
  export const IFixitIcon: Component
  export const IFoodIcon: Component
  export const ImDbIcon: Component
  export const ImgurIcon: Component
  export const IndeedIcon: Component
  export const InfluxDbIcon: Component
  export const InkscapeIcon: Component
  export const InstacartIcon: Component
  export const InstagramIcon: Component
  export const InstapaperIcon: Component
  export const IntelIcon: Component
  export const IntelliJIdeaIcon: Component
  export const IntercomIcon: Component
  export const InternetArchiveIcon: Component
  export const InternetExplorerIcon: Component
  export const InVisionIcon: Component
  export const InvoiceNinjaIcon: Component
  export const IoBrokerIcon: Component
  export const IonicIcon: Component
  export const IOsIcon: Component
  export const IpfsIcon: Component
  export const IssuuIcon: Component
  export const ItchIoIcon: Component
  export const ITunesIcon: Component
  export const JabberIcon: Component
  export const JavaIcon: Component
  export const JavaScriptIcon: Component
  export const JcbIcon: Component
  export const JekyllIcon: Component
  export const JenkinsIcon: Component
  export const JenkinsXIcon: Component
  export const JestIcon: Component
  export const JetIcon: Component
  export const JetBrainsIcon: Component
  export const JinjaIcon: Component
  export const JiraIcon: Component
  export const JoomlaIcon: Component
  export const JQueryIcon: Component
  export const JsDelivrIcon: Component
  export const JsFiddleIcon: Component
  export const JsonIcon: Component
  export const JupyterIcon: Component
  export const JustEatIcon: Component
  export const JustGivingIcon: Component
  export const KaggleIcon: Component
  export const KaiOsIcon: Component
  export const KasperskyIcon: Component
  export const KatanaIcon: Component
  export const KeePassXcIcon: Component
  export const KenticoIcon: Component
  export const KerasIcon: Component
  export const KeybaseIcon: Component
  export const KeyCdnIcon: Component
  export const KhanAcademyIcon: Component
  export const KhronosGroupIcon: Component
  export const KibanaIcon: Component
  export const KickstarterIcon: Component
  export const KikIcon: Component
  export const KirbyIcon: Component
  export const KlmIcon: Component
  export const KloutIcon: Component
  export const KnownIcon: Component
  export const KoFiIcon: Component
  export const KodiIcon: Component
  export const KodingIcon: Component
  export const KotlinIcon: Component
  export const KritaIcon: Component
  export const KubernetesIcon: Component
  export const KyoceraIcon: Component
  export const LabViewIcon: Component
  export const LaravelIcon: Component
  export const LaravelHorizonIcon: Component
  export const LaravelNovaIcon: Component
  export const LastFmIcon: Component
  export const LastPassIcon: Component
  export const LaTeXIcon: Component
  export const LaunchpadIcon: Component
  export const LeetCodeIcon: Component
  export const LenovoIcon: Component
  export const LetSEncryptIcon: Component
  export const LetterboxdIcon: Component
  export const LgIcon: Component
  export const LgtmIcon: Component
  export const LiberapayIcon: Component
  export const LibraryThingIcon: Component
  export const LibreOfficeIcon: Component
  export const LighthouseIcon: Component
  export const LineIcon: Component
  export const LineWebtoonIcon: Component
  export const LinkedInIcon: Component
  export const LinodeIcon: Component
  export const LinuxIcon: Component
  export const LinuxFoundationIcon: Component
  export const LinuxMintIcon: Component
  export const LitecoinIcon: Component
  export const LiveJournalIcon: Component
  export const LivestreamIcon: Component
  export const LlvmIcon: Component
  export const LmmsIcon: Component
  export const LogMeInIcon: Component
  export const LogstashIcon: Component
  export const LoopIcon: Component
  export const LuaIcon: Component
  export const LufthansaIcon: Component
  export const LumenIcon: Component
  export const LyftIcon: Component
  export const MaasIcon: Component
  export const MacySIcon: Component
  export const MagentoIcon: Component
  export const MagiskIcon: Component
  export const MailRuIcon: Component
  export const MailChimpIcon: Component
  export const MakerBotIcon: Component
  export const ManageIqIcon: Component
  export const ManjaroIcon: Component
  export const MapboxIcon: Component
  export const MariaDbIcon: Component
  export const MariaDbFoundationIcon: Component
  export const MarkdownIcon: Component
  export const MarketoIcon: Component
  export const MasterCardIcon: Component
  export const MastodonIcon: Component
  export const MaterialDesignIcon: Component
  export const MaterialDesignIconsIcon: Component
  export const MaterialUiIcon: Component
  export const MathworksIcon: Component
  export const MatrixIcon: Component
  export const MattermostIcon: Component
  export const MatternetIcon: Component
  export const McAfeeIcon: Component
  export const MdnWebDocsIcon: Component
  export const MediaFireIcon: Component
  export const MediaTempleIcon: Component
  export const MediumIcon: Component
  export const MeetupIcon: Component
  export const MegaIcon: Component
  export const MendeleyIcon: Component
  export const MercedesIcon: Component
  export const MessengerIcon: Component
  export const MeteorIcon: Component
  export const MicroBlogIcon: Component
  export const MicrogeneticsIcon: Component
  export const MicrosoftIcon: Component
  export const MicrosoftAccessIcon: Component
  export const MicrosoftAzureIcon: Component
  export const MicrosoftEdgeIcon: Component
  export const MicrosoftExcelIcon: Component
  export const MicrosoftOfficeIcon: Component
  export const MicrosoftOneDriveIcon: Component
  export const MicrosoftOneNoteIcon: Component
  export const MicrosoftOutlookIcon: Component
  export const MicrosoftPowerPointIcon: Component
  export const MicrosoftSqlServerIcon: Component
  export const MicrosoftTeamsIcon: Component
  export const MicrosoftWordIcon: Component
  export const MicroStrategyIcon: Component
  export const MidiIcon: Component
  export const MindsIcon: Component
  export const MinetestIcon: Component
  export const MinutemailerIcon: Component
  export const MixIcon: Component
  export const MixcloudIcon: Component
  export const MixerIcon: Component
  export const MochaIcon: Component
  export const MojangIcon: Component
  export const MoneroIcon: Component
  export const MongoDbIcon: Component
  export const MonkeyTieIcon: Component
  export const MonogramIcon: Component
  export const MonsterIcon: Component
  export const MonzoIcon: Component
  export const MooIcon: Component
  export const MozillaIcon: Component
  export const MozillaFirefoxIcon: Component
  export const MuseScoreIcon: Component
  export const MxLinuxIcon: Component
  export const MyspaceIcon: Component
  export const MySqlIcon: Component
  export const NativeScriptIcon: Component
  export const NdrIcon: Component
  export const NecIcon: Component
  export const Neo4jIcon: Component
  export const NeovimIcon: Component
  export const NetAppIcon: Component
  export const NetflixIcon: Component
  export const NetlifyIcon: Component
  export const NewYorkTimesIcon: Component
  export const NextJsIcon: Component
  export const NextcloudIcon: Component
  export const NextdoorIcon: Component
  export const NfcIcon: Component
  export const NginxIcon: Component
  export const NimIcon: Component
  export const NintendoIcon: Component
  export const Nintendo_3DsIcon: Component
  export const NintendoGameCubeIcon: Component
  export const NintendoSwitchIcon: Component
  export const NixOsIcon: Component
  export const NodeRedIcon: Component
  export const NodeJsIcon: Component
  export const NodemonIcon: Component
  export const NokiaIcon: Component
  export const NotionIcon: Component
  export const NotistIcon: Component
  export const NpmIcon: Component
  export const NucleoIcon: Component
  export const NuGetIcon: Component
  export const NukeIcon: Component
  export const NutanixIcon: Component
  export const NuxtJsIcon: Component
  export const NvidiaIcon: Component
  export const ObsStudioIcon: Component
  export const OCamlIcon: Component
  export const OctaveIcon: Component
  export const OctopusDeployIcon: Component
  export const OculusIcon: Component
  export const OdnoklassnikiIcon: Component
  export const OpelIcon: Component
  export const OpenAccessIcon: Component
  export const OpenCollectiveIcon: Component
  export const OpenContainersInitiativeIcon: Component
  export const OpenSourceInitiativeIcon: Component
  export const OpenApiInitiativeIcon: Component
  export const OpenBsdIcon: Component
  export const OpenGlIcon: Component
  export const OpenIdIcon: Component
  export const OpenSslIcon: Component
  export const OpenStreetMapIcon: Component
  export const OpenSuseIcon: Component
  export const OpenVpnIcon: Component
  export const OperaIcon: Component
  export const OpsgenieIcon: Component
  export const OpsLevelIcon: Component
  export const OracleIcon: Component
  export const OrcidIcon: Component
  export const OriginIcon: Component
  export const OsmcIcon: Component
  export const OvercastIcon: Component
  export const OverleafIcon: Component
  export const OvhIcon: Component
  export const PagekitIcon: Component
  export const PalantirIcon: Component
  export const PaloAltoSoftwareIcon: Component
  export const PandoraIcon: Component
  export const PantheonIcon: Component
  export const ParitySubstrateIcon: Component
  export const ParseLyIcon: Component
  export const PastebinIcon: Component
  export const PatreonIcon: Component
  export const PayPalIcon: Component
  export const PeerTubeIcon: Component
  export const PepsiIcon: Component
  export const PeriscopeIcon: Component
  export const PeugeotIcon: Component
  export const PexelsIcon: Component
  export const PhotocrowdIcon: Component
  export const PhpIcon: Component
  export const PiHoleIcon: Component
  export const PicartoTvIcon: Component
  export const PinboardIcon: Component
  export const PingdomIcon: Component
  export const PingupIcon: Component
  export const PinterestIcon: Component
  export const PivotalTrackerIcon: Component
  export const PixabayIcon: Component
  export const PjsipIcon: Component
  export const PlanGridIcon: Component
  export const PlayerFmIcon: Component
  export const PlayerMeIcon: Component
  export const PlayStationIcon: Component
  export const PlayStation_3Icon: Component
  export const PlayStation_4Icon: Component
  export const PleromaIcon: Component
  export const PleskIcon: Component
  export const PlexIcon: Component
  export const PluralsightIcon: Component
  export const PlurkIcon: Component
  export const PocketIcon: Component
  export const PocketCastsIcon: Component
  export const PolymerProjectIcon: Component
  export const PostgreSqlIcon: Component
  export const PostmanIcon: Component
  export const PostwomanIcon: Component
  export const PowerShellIcon: Component
  export const PrCoIcon: Component
  export const PreCommitIcon: Component
  export const PrestaShopIcon: Component
  export const PrettierIcon: Component
  export const PrismicIcon: Component
  export const ProbotIcon: Component
  export const ProcessWireIcon: Component
  export const ProductHuntIcon: Component
  export const PrometheusIcon: Component
  export const ProtoIoIcon: Component
  export const ProtocolsIoIcon: Component
  export const ProtonMailIcon: Component
  export const ProxmoxIcon: Component
  export const PublonsIcon: Component
  export const PureScriptIcon: Component
  export const PyPiIcon: Component
  export const PythonIcon: Component
  export const PyTorchIcon: Component
  export const PyUpIcon: Component
  export const QemuIcon: Component
  export const QgisIcon: Component
  export const QiIcon: Component
  export const QiitaIcon: Component
  export const QualcommIcon: Component
  export const QualtricsIcon: Component
  export const QuantcastIcon: Component
  export const QuantopianIcon: Component
  export const QuarkusIcon: Component
  export const QuestIcon: Component
  export const QuickTimeIcon: Component
  export const QuipIcon: Component
  export const QuoraIcon: Component
  export const QwiklabsIcon: Component
  export const QzoneIcon: Component
  export const RIcon: Component
  export const RabbitMqIcon: Component
  export const RadioPublicIcon: Component
  export const RailsIcon: Component
  export const RaspberryPiIcon: Component
  export const ReactIcon: Component
  export const ReactRouterIcon: Component
  export const ReactOsIcon: Component
  export const ReadTheDocsIcon: Component
  export const RealmIcon: Component
  export const ReasonIcon: Component
  export const ReasonStudiosIcon: Component
  export const RedHatIcon: Component
  export const RedHatOpenShiftIcon: Component
  export const RedbubbleIcon: Component
  export const RedditIcon: Component
  export const RedisIcon: Component
  export const ReduxIcon: Component
  export const RenrenIcon: Component
  export const ReplItIcon: Component
  export const ResearchGateIcon: Component
  export const ReverbNationIcon: Component
  export const RhinocerosIcon: Component
  export const RiotIcon: Component
  export const RippleIcon: Component
  export const RiseupIcon: Component
  export const RollupJsIcon: Component
  export const RootsIcon: Component
  export const RoundcubeIcon: Component
  export const RssIcon: Component
  export const RStudioIcon: Component
  export const RtlzweiIcon: Component
  export const RubyIcon: Component
  export const RubyGemsIcon: Component
  export const RunkeeperIcon: Component
  export const RustIcon: Component
  export const SafariIcon: Component
  export const SahibindenIcon: Component
  export const SalesforceIcon: Component
  export const SaltStackIcon: Component
  export const SamsungIcon: Component
  export const SamsungPayIcon: Component
  export const SapIcon: Component
  export const SassIcon: Component
  export const Sat_1Icon: Component
  export const SauceLabsIcon: Component
  export const ScalaIcon: Component
  export const ScalewayIcon: Component
  export const ScribdIcon: Component
  export const ScrutinizerCiIcon: Component
  export const SeagateIcon: Component
  export const SeatIcon: Component
  export const SegaIcon: Component
  export const SellfyIcon: Component
  export const SemanticWebIcon: Component
  export const SemaphoreCiIcon: Component
  export const SenchaIcon: Component
  export const SensuIcon: Component
  export const SentryIcon: Component
  export const ServerFaultIcon: Component
  export const ServerlessIcon: Component
  export const ShazamIcon: Component
  export const ShellIcon: Component
  export const ShopifyIcon: Component
  export const ShowpadIcon: Component
  export const SiemensIcon: Component
  export const SignalIcon: Component
  export const SimpleIconsIcon: Component
  export const SinaWeiboIcon: Component
  export const SitePointIcon: Component
  export const SketchIcon: Component
  export const SkillshareIcon: Component
  export const SkylinerIcon: Component
  export const SkypeIcon: Component
  export const SkypeForBusinessIcon: Component
  export const SlackIcon: Component
  export const SlackwareIcon: Component
  export const SlashdotIcon: Component
  export const SlickPicIcon: Component
  export const SlidesIcon: Component
  export const SmashingMagazineIcon: Component
  export const SmugMugIcon: Component
  export const SnapchatIcon: Component
  export const SnapcraftIcon: Component
  export const SnykIcon: Component
  export const Society6Icon: Component
  export const SocketIoIcon: Component
  export const SogouIcon: Component
  export const SolusIcon: Component
  export const SonarCloudIcon: Component
  export const SonarLintIcon: Component
  export const SonarQubeIcon: Component
  export const SonarSourceIcon: Component
  export const SongkickIcon: Component
  export const SonicWallIcon: Component
  export const SonosIcon: Component
  export const SoundCloudIcon: Component
  export const SourceEngineIcon: Component
  export const SourceForgeIcon: Component
  export const SourcegraphIcon: Component
  export const SpacemacsIcon: Component
  export const SpaceXIcon: Component
  export const SparkFunIcon: Component
  export const SparkPostIcon: Component
  export const SpdxIcon: Component
  export const SpeakerDeckIcon: Component
  export const SpectrumIcon: Component
  export const SpinnakerIcon: Component
  export const SpotifyIcon: Component
  export const SpotlightIcon: Component
  export const SpreakerIcon: Component
  export const SpringIcon: Component
  export const SprintIcon: Component
  export const SquareIcon: Component
  export const SquareEnixIcon: Component
  export const SquarespaceIcon: Component
  export const StackExchangeIcon: Component
  export const StackOverflowIcon: Component
  export const StackbitIcon: Component
  export const StackPathIcon: Component
  export const StackShareIcon: Component
  export const StadiaIcon: Component
  export const StatamicIcon: Component
  export const StaticmanIcon: Component
  export const StatuspageIcon: Component
  export const SteamIcon: Component
  export const SteamworksIcon: Component
  export const SteemIcon: Component
  export const SteemitIcon: Component
  export const SteinbergIcon: Component
  export const StencylIcon: Component
  export const StitcherIcon: Component
  export const StorifyIcon: Component
  export const StorybookIcon: Component
  export const StrapiIcon: Component
  export const StravaIcon: Component
  export const StripeIcon: Component
  export const StrongSwanIcon: Component
  export const StubHubIcon: Component
  export const StyledComponentsIcon: Component
  export const StyleShareIcon: Component
  export const StylusIcon: Component
  export const SublimeTextIcon: Component
  export const SubversionIcon: Component
  export const SuperUserIcon: Component
  export const SvelteIcon: Component
  export const SvgIcon: Component
  export const SvgoIcon: Component
  export const SwaggerIcon: Component
  export const SwarmIcon: Component
  export const SwiftIcon: Component
  export const SymantecIcon: Component
  export const SymfonyIcon: Component
  export const SymphonyIcon: Component
  export const SynologyIcon: Component
  export const TMobileIcon: Component
  export const TableauIcon: Component
  export const TailsIcon: Component
  export const TailwindCssIcon: Component
  export const TapasIcon: Component
  export const TeamViewerIcon: Component
  export const TedIcon: Component
  export const TeespringIcon: Component
  export const Tele5Icon: Component
  export const TelegramIcon: Component
  export const TencentQqIcon: Component
  export const TencentWeiboIcon: Component
  export const TensorFlowIcon: Component
  export const TeradataIcon: Component
  export const TerraformIcon: Component
  export const TeslaIcon: Component
  export const TheMightyIcon: Component
  export const TheMovieDatabaseIcon: Component
  export const TheRegisterIcon: Component
  export const TidalIcon: Component
  export const TideIcon: Component
  export const TikTokIcon: Component
  export const TimescaleIcon: Component
  export const TinderIcon: Component
  export const TodoistIcon: Component
  export const TogglIcon: Component
  export const TomorrowlandIcon: Component
  export const TopcoderIcon: Component
  export const ToptalIcon: Component
  export const TorIcon: Component
  export const ToshibaIcon: Component
  export const TrainerRoadIcon: Component
  export const TraktIcon: Component
  export const TransportForIrelandIcon: Component
  export const TravisCiIcon: Component
  export const TreehouseIcon: Component
  export const TrelloIcon: Component
  export const TrendMicroIcon: Component
  export const TripadvisorIcon: Component
  export const TruliaIcon: Component
  export const TrustpilotIcon: Component
  export const TumblrIcon: Component
  export const TurkishAirlinesIcon: Component
  export const TwilioIcon: Component
  export const TwitchIcon: Component
  export const TwitterIcon: Component
  export const TwooIcon: Component
  export const TypeScriptIcon: Component
  export const Typo3Icon: Component
  export const UberIcon: Component
  export const UberEatsIcon: Component
  export const UbisoftIcon: Component
  export const UBlockOriginIcon: Component
  export const UbuntuIcon: Component
  export const UdacityIcon: Component
  export const UdemyIcon: Component
  export const UIkitIcon: Component
  export const UmbracoIcon: Component
  export const UnicodeIcon: Component
  export const UnityIcon: Component
  export const UnrealEngineIcon: Component
  export const UnsplashIcon: Component
  export const UntangleIcon: Component
  export const UntappdIcon: Component
  export const UpworkIcon: Component
  export const VIcon: Component
  export const V8Icon: Component
  export const VagrantIcon: Component
  export const ValveIcon: Component
  export const VeeamIcon: Component
  export const VenmoIcon: Component
  export const VeritasIcon: Component
  export const VerizonIcon: Component
  export const ViadeoIcon: Component
  export const ViberIcon: Component
  export const VimIcon: Component
  export const VimeoIcon: Component
  export const VineIcon: Component
  export const VirbIcon: Component
  export const VisaIcon: Component
  export const VisualStudioIcon: Component
  export const VisualStudioCodeIcon: Component
  export const VkIcon: Component
  export const VlcMediaPlayerIcon: Component
  export const VMwareIcon: Component
  export const VodafoneIcon: Component
  export const VolkswagenIcon: Component
  export const VscoIcon: Component
  export const VueJsIcon: Component
  export const VuetifyIcon: Component
  export const VulkanIcon: Component
  export const W3CIcon: Component
  export const WattpadIcon: Component
  export const WazeIcon: Component
  export const WearOsIcon: Component
  export const WeasylIcon: Component
  export const WebAssemblyIcon: Component
  export const WebAuthnIcon: Component
  export const WebcomponentsOrgIcon: Component
  export const WebGlIcon: Component
  export const WebminIcon: Component
  export const WebpackIcon: Component
  export const WebRtcIcon: Component
  export const WebStormIcon: Component
  export const WeChatIcon: Component
  export const WhatsAppIcon: Component
  export const WhenIWorkIcon: Component
  export const WhiteSourceIcon: Component
  export const WiiIcon: Component
  export const WiiUIcon: Component
  export const WikipediaIcon: Component
  export const WindowsIcon: Component
  export const WireIcon: Component
  export const WireGuardIcon: Component
  export const WishIcon: Component
  export const WixIcon: Component
  export const WolframIcon: Component
  export const WolframLanguageIcon: Component
  export const WolframMathematicaIcon: Component
  export const WooIcon: Component
  export const WooCommerceIcon: Component
  export const WordPressIcon: Component
  export const WorkplaceIcon: Component
  export const WpEngineIcon: Component
  export const WpRocketIcon: Component
  export const WriteAsIcon: Component
  export const XPackIcon: Component
  export const XOrgIcon: Component
  export const XamarinIcon: Component
  export const XamppIcon: Component
  export const XboxIcon: Component
  export const XcodeIcon: Component
  export const XdaDevelopersIcon: Component
  export const XeroIcon: Component
  export const XfceIcon: Component
  export const XiaomiIcon: Component
  export const XingIcon: Component
  export const XmppIcon: Component
  export const XrpIcon: Component
  export const XSplitIcon: Component
  export const YCombinatorIcon: Component
  export const YahooIcon: Component
  export const YamahaCorporationIcon: Component
  export const YamahaMotorCorporationIcon: Component
  export const YammerIcon: Component
  export const YandexIcon: Component
  export const YarnIcon: Component
  export const YelpIcon: Component
  export const YouTubeIcon: Component
  export const YouTubeGamingIcon: Component
  export const YouTubeTvIcon: Component
  export const ZWaveIcon: Component
  export const ZalandoIcon: Component
  export const ZapierIcon: Component
  export const ZdfIcon: Component
  export const ZeitIcon: Component
  export const ZendIcon: Component
  export const ZendFrameworkIcon: Component
  export const ZendeskIcon: Component
  export const ZeroMqIcon: Component
  export const ZerplyIcon: Component
  export const ZhihuIcon: Component
  export const ZigbeeIcon: Component
  export const ZillowIcon: Component
  export const ZingatIcon: Component
  export const ZoomIcon: Component
  export const ZorinIcon: Component
  export const ZulipIcon: Component
}
